#include "Common.hh"
#define BUILDTAG PACKAGE_NAME, PACKAGE_VERSION " / 6108", "2014-03-28 16:24:03 UTC", "Linux 2.6.32-54-generic i686", "'VALUE_CHECK_WANTED=yes' 'VALUE_HISTORY_WANTED=yes' 'DYNAMIC_LOG_WANTED=yes' 'ASSERT_LEVEL_WANTED=2' 'PRINT_SEMA_WANTED=yes' 'VISIBLE_MARKERS_WANTED=yes'"
